title: Mapping for Academic Publication
remote_theme: ubc-library-rc/rc-theme
color_scheme: rc
github_repo_url: "https://ubc-library-rc.github.io/gis-reference-mapping/" 

# license information for workshop content
license_name: "Creative Commons Attribution 4.0 International License"
license_url: "http://creativecommons.org/licenses/by/4.0/"
license_image_url: "https://i.creativecommons.org/l/by/4.0/88x31.png"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache
